csv_reader_test:
	g++ -std=c++0x csv_reader_test.cc -o csv_reader_test.o csv_reader.cc -I $HOME/google-library/include -L $HOME/google-library/lib -lgflags -lglog

clean:
	rm -f *.o *.out
	rm -f *.txt
